### ISSUE TITLE
add virtual handle for comments

### ISSUE THREAD

**Issue by davidholyko** [m-d-h-s/mdhs-blog-backend#12]
blog has

```
blogSchema.virtual('handle', {
  ref: 'User',
  localField: 'owner',
  foreignField: '_id'
})
```

and add same for comment

**Comment by freef** [comment]
Not sure I'm following this issue. Blog already returns the user name as of most recent pr

**Comment by davidholyko** [comment]
comment doesnt have a virtual handle as of now, we want to add this

**Comment by davidholyko** [comment]
o, nvm im probably not on the most recent dev branch

**Comment by freef** [comment]
Most recent pr should have it... I'll check when I get home
